// generated by mBlock5 for <your product>
// codes make you happy

#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>

void _delay(float seconds) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
}

void setup() {
  pinMode(11,OUTPUT);
  pinMode(10,OUTPUT);
  pinMode(9,OUTPUT);
  pinMode(8,OUTPUT);
  while(1) {
      digitalWrite(11,1);
      _delay(0.1);
      digitalWrite(11,0);
      digitalWrite(10,1);
      _delay(0.1);
      digitalWrite(10,0);
      digitalWrite(9,1);
      _delay(0.1);
      digitalWrite(9,0);
      digitalWrite(8,1);
      _delay(0.1);
      digitalWrite(8,0);

      _loop();
  }

}

void _loop() {
}

void loop() {
  _loop();
}
